/*
 * AgentPanel.java
 *
 * Created on 16. November 2005, 22:29
 */

package at.lux.fotoannotation.dialogs;

/**
 *
 * @author  Mathias
 */
public class AgentPanel extends javax.swing.JPanel {
    
    /** Creates new form AgentPanel */
    public AgentPanel() {
        initComponents();
    }

    public String getAddress() {
        return address.getText();
    }

    public String getDescription() {
        return description.getText();
    }

    public String getEmail() {
        return description.getText();
    }

    public String getFamilyName() {
        return familyName.getText();
    }

    public String getFax() {
        return fax.getText();
    }

    public String getGivenName() {
        return givenName.getText();
    }

    public String getNickname() {
        return nickname.getText();
    }

    public String getOrganization() {
        return organization.getText();
    }

    public String getPhone() {
        return phone.getText();
    }

    public String getUrl() {
        return url.getText();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        gnameLabel = new javax.swing.JLabel();
        fnameLabel = new javax.swing.JLabel();
        organizationLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        phoneLabel = new javax.swing.JLabel();
        faxLabel = new javax.swing.JLabel();
        urlLabel = new javax.swing.JLabel();
        nickLabel = new javax.swing.JLabel();
        givenName = new javax.swing.JTextField();
        familyName = new javax.swing.JTextField();
        organization = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        fax = new javax.swing.JTextField();
        url = new javax.swing.JTextField();
        nickname = new javax.swing.JTextField();
        addressLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        descriptionLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        description = new javax.swing.JTextArea();

        gnameLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        gnameLabel.setText("Given Name:");
        gnameLabel.setToolTipText("Bold fields are mandatory");

        fnameLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        fnameLabel.setText("Family Name:");
        fnameLabel.setToolTipText("Bold fields are mandatory");

        organizationLabel.setText("Organization:");

        emailLabel.setText("Email:");

        phoneLabel.setText("Phone:");

        faxLabel.setText("Fax:");

        urlLabel.setText("URL:");

        nickLabel.setText("Nickname:");

        givenName.setToolTipText("Put in the first name of the person, e.g. \"Peter\"");

        familyName.setToolTipText("Put in the family name of the person.");

        addressLabel.setText("Adresss:");

        address.setColumns(20);
        address.setFont(new java.awt.Font("Tahoma", 0, 11));
        address.setRows(3);
        address.setToolTipText("Address of the person");
        jScrollPane1.setViewportView(address);

        descriptionLabel.setText("Description:");

        description.setColumns(20);
        description.setFont(new java.awt.Font("Tahoma", 0, 11));
        description.setRows(3);
        description.setToolTipText("Description of the person defined by the form.");
        jScrollPane2.setViewportView(description);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(gnameLabel)
                    .add(emailLabel)
                    .add(phoneLabel)
                    .add(faxLabel)
                    .add(urlLabel)
                    .add(nickLabel)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(fnameLabel)
                            .add(organizationLabel))
                        .add(14, 14, 14)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(familyName, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, email, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, phone, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, fax, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, url, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, nickname, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, organization, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, givenName, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))))
                .add(19, 19, 19)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(addressLabel)
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(descriptionLabel))
                    .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(gnameLabel)
                    .add(addressLabel)
                    .add(givenName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(fnameLabel)
                            .add(familyName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(organizationLabel)
                            .add(organization, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(emailLabel)
                            .add(email, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(phoneLabel)
                            .add(phone, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(descriptionLabel)))
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 70, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(faxLabel)
                            .add(fax, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(urlLabel)
                            .add(url, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(nickLabel)
                            .add(nickname, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 72, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea address;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextArea description;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JTextField email;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField familyName;
    private javax.swing.JTextField fax;
    private javax.swing.JLabel faxLabel;
    private javax.swing.JLabel fnameLabel;
    private javax.swing.JTextField givenName;
    private javax.swing.JLabel gnameLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel nickLabel;
    private javax.swing.JTextField nickname;
    private javax.swing.JTextField organization;
    private javax.swing.JLabel organizationLabel;
    private javax.swing.JTextField phone;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JTextField url;
    private javax.swing.JLabel urlLabel;
    // End of variables declaration//GEN-END:variables
    
    
}
