/*
 * ConfigurationSelectionPanel.java
 *
 * Created on 10. Jänner 2006, 11:13
 */

package at.lux.fotoretrieval.panels;

import java.awt.*;

/**
 *
 * @author  mlux
 */
public class ConfigurationSelectionPanel extends javax.swing.JPanel {
    protected Color selectedBackgroundColor = Color.decode("#d8ddf9");

    /** Creates new form ConfigurationSelectionPanel */
    public ConfigurationSelectionPanel() {
        initComponents();
        mainConfigButton.setBackground(selectedBackgroundColor);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        outerPanel = new javax.swing.JPanel();
        innerPanel = new javax.swing.JPanel();
        mainConfigButton = new javax.swing.JButton();
        clusteringConfigButton = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        setForeground(new java.awt.Color(255, 255, 255));
        setToolTipText("Select which part of Emir you want to configure.");
        outerPanel.setLayout(new java.awt.BorderLayout());

        outerPanel.setBackground(new java.awt.Color(255, 255, 255));
        outerPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        innerPanel.setLayout(new java.awt.GridLayout(-1, 1));

        innerPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainConfigButton.setBackground(new java.awt.Color(255, 255, 255));
        mainConfigButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/config/settings.png")));
        mainConfigButton.setText("<html>General</html>");
        mainConfigButton.setToolTipText("Main configuration");
        mainConfigButton.setActionCommand("mainConfig");
        mainConfigButton.setBorderPainted(false);
        mainConfigButton.setFocusPainted(false);
        mainConfigButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        mainConfigButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        mainConfigButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainConfigButtonActionPerformed(evt);
            }
        });

        innerPanel.add(mainConfigButton);

        clusteringConfigButton.setBackground(new java.awt.Color(255, 255, 255));
        clusteringConfigButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/config/clustering.png")));
        clusteringConfigButton.setText("<html>Clustering<br>& MDS</html>");
        clusteringConfigButton.setToolTipText("Configuration for Clustering.");
        clusteringConfigButton.setActionCommand("clusteringConfig");
        clusteringConfigButton.setBorderPainted(false);
        clusteringConfigButton.setFocusPainted(false);
        clusteringConfigButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        clusteringConfigButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        clusteringConfigButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clusteringConfigButtonActionPerformed(evt);
            }
        });

        innerPanel.add(clusteringConfigButton);

        outerPanel.add(innerPanel, java.awt.BorderLayout.NORTH);

        add(outerPanel, java.awt.BorderLayout.CENTER);

    }// </editor-fold>//GEN-END:initComponents

    private void clusteringConfigButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clusteringConfigButtonActionPerformed
        mainConfigButton.setBackground(Color.white);
        clusteringConfigButton.setBackground(selectedBackgroundColor);
    }//GEN-LAST:event_clusteringConfigButtonActionPerformed

    private void mainConfigButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainConfigButtonActionPerformed
        mainConfigButton.setBackground(selectedBackgroundColor);
        clusteringConfigButton.setBackground(Color.white);
    }//GEN-LAST:event_mainConfigButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton clusteringConfigButton;
    private javax.swing.JPanel innerPanel;
    public javax.swing.JButton mainConfigButton;
    private javax.swing.JPanel outerPanel;
    // End of variables declaration//GEN-END:variables

}
