/*
 * MdsConfiguration.java
 *
 * Created on 10. Jänner 2006, 10:54
 */

package at.lux.fotoretrieval.panels;

/**
 *
 * @author  mlux
 */
public class MdsConfiguration extends javax.swing.JPanel {
    String[] metrics = new String[] { "ScalableColor descriptor", "ColorLayout descriptor", "DominantColor descriptor",
            "EdgeHistogram descriptor", "Semantic descriptions (MCS)", "Semantic descriptions (STM)",
            "Semantic descriptions (Berretti)", "Semantic descriptions (Vector Space)" };
    String[] algorithms = new String[] { "HAC", "Suffix Tree Clustering" };
    
    /** Creates new form MdsConfiguration */
    public MdsConfiguration() {
        initComponents();
        frameTitle.title.setText("MDS & Clustering");
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        fdpGroupLabel = new javax.swing.JLabel();
        gravityLabel = new javax.swing.JLabel();
        minDistanceLabel = new javax.swing.JLabel();
        dLabel = new javax.swing.JLabel();
        wLabel = new javax.swing.JLabel();
        rLabel = new javax.swing.JLabel();
        gravity = new javax.swing.JTextField();
        minDistance = new javax.swing.JTextField();
        w = new javax.swing.JTextField();
        d = new javax.swing.JTextField();
        r = new javax.swing.JTextField();
        mdsgroupLabel = new javax.swing.JLabel();
        stepAwaitLabel = new javax.swing.JLabel();
        startWaitLabel = new javax.swing.JLabel();
        stopConditionLabel = new javax.swing.JLabel();
        stepWait = new javax.swing.JTextField();
        startWait = new javax.swing.JTextField();
        stopCondition = new javax.swing.JTextField();
        clusteringAlgorithmLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        clusteringMetric = new javax.swing.JComboBox();
        clusteringAlgorithm = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        fdpMetric = new javax.swing.JComboBox();
        frameTitle = new at.lux.fotoannotation.panels.components.FrameTitle();

        fdpGroupLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        fdpGroupLabel.setText("FDP Algorithmic parameters:");

        gravityLabel.setText("Gravity:");

        minDistanceLabel.setText("Min. distance:");

        dLabel.setText("Separation:");

        wLabel.setText("Attraction:");

        rLabel.setText("Repulsion:");

        gravity.setToolTipText("Constant gravitation of points, should be related somehow with the number of points, the more points the smaller the gravitation.");

        minDistance.setToolTipText("Defines what is the minimum distance simulated for points at the same location.");

        w.setToolTipText("Tunes the atraction of points the higher this value the smaller the attraction. Default value is 1.");

        d.setToolTipText("This parameter makes cluster separation more significant if value is bigger than 1.");

        r.setToolTipText("Parameter prevents points from coming too close to each other. Value is normally 1, allowed are values from (0, infinite).");

        mdsgroupLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        mdsgroupLabel.setText("MDS Visualization parameters:");

        stepAwaitLabel.setText("Step wait:");

        startWaitLabel.setText("Start wait:");

        stopConditionLabel.setText("Stop condition:");

        clusteringAlgorithmLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        clusteringAlgorithmLabel.setText("Clustering Algorithm:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setText("Clustering Metric:");

        clusteringMetric.setModel(new javax.swing.DefaultComboBoxModel(metrics));
        clusteringMetric.setEnabled(false);

        clusteringAlgorithm.setModel(new javax.swing.DefaultComboBoxModel(algorithms));
        clusteringAlgorithm.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setText("FDP Metric:");

        fdpMetric.setModel(new javax.swing.DefaultComboBoxModel(metrics));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                        .add(layout.createSequentialGroup()
                            .add(mdsgroupLabel)
                            .add(66, 66, 66))
                        .add(layout.createSequentialGroup()
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(layout.createSequentialGroup()
                                    .add(10, 10, 10)
                                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                        .add(layout.createSequentialGroup()
                                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                .add(stopConditionLabel)
                                                .add(startWaitLabel)
                                                .add(stepAwaitLabel))
                                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                .add(stepWait, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                                                .add(startWait, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                                                .add(stopCondition, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)))
                                        .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                .add(minDistanceLabel)
                                                .add(wLabel)
                                                .add(dLabel)
                                                .add(rLabel)
                                                .add(gravityLabel))
                                            .add(12, 12, 12)
                                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                                .add(r)
                                                .add(d)
                                                .add(w)
                                                .add(minDistance)
                                                .add(gravity, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 103, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))))
                                .add(fdpGroupLabel))
                            .add(17, 17, 17)
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(layout.createSequentialGroup()
                                    .add(10, 10, 10)
                                    .add(fdpMetric, 0, 109, Short.MAX_VALUE))
                                .add(jLabel2)
                                .add(clusteringAlgorithmLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(jLabel1)
                                .add(layout.createSequentialGroup()
                                    .add(10, 10, 10)
                                    .add(clusteringAlgorithm, 0, 171, Short.MAX_VALUE))
                                .add(layout.createSequentialGroup()
                                    .add(10, 10, 10)
                                    .add(clusteringMetric, 0, 171, Short.MAX_VALUE)))))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, frameTitle, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(frameTitle, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(17, 17, 17)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(fdpGroupLabel)
                    .add(jLabel1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(gravityLabel)
                    .add(gravity, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(clusteringMetric, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(minDistanceLabel)
                    .add(minDistance, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(clusteringAlgorithmLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(wLabel)
                    .add(w, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(clusteringAlgorithm, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(dLabel)
                    .add(d, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(rLabel)
                    .add(r, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(fdpMetric, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(mdsgroupLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(stepAwaitLabel)
                        .add(stepWait, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(26, 26, 26)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(startWaitLabel)
                            .add(startWait, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(stopConditionLabel)
                            .add(stopCondition, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox clusteringAlgorithm;
    public javax.swing.JLabel clusteringAlgorithmLabel;
    public javax.swing.JComboBox clusteringMetric;
    public javax.swing.JTextField d;
    public javax.swing.JLabel dLabel;
    public javax.swing.JLabel fdpGroupLabel;
    public javax.swing.JComboBox fdpMetric;
    public at.lux.fotoannotation.panels.components.FrameTitle frameTitle;
    public javax.swing.JTextField gravity;
    public javax.swing.JLabel gravityLabel;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel mdsgroupLabel;
    public javax.swing.JTextField minDistance;
    public javax.swing.JLabel minDistanceLabel;
    public javax.swing.JTextField r;
    public javax.swing.JLabel rLabel;
    public javax.swing.JTextField startWait;
    public javax.swing.JLabel startWaitLabel;
    public javax.swing.JLabel stepAwaitLabel;
    public javax.swing.JTextField stepWait;
    public javax.swing.JTextField stopCondition;
    public javax.swing.JLabel stopConditionLabel;
    public javax.swing.JTextField w;
    public javax.swing.JLabel wLabel;
    // End of variables declaration//GEN-END:variables
    
}
